// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"blogs/app/admin/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthToken},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/users/login",
					Handler: LoginHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/user/menus",
					Handler: UserMenusHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/report",
					Handler: ReportHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/users/area",
					Handler: AreaDataHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/",
					Handler: SysInfoHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/categories/search",
					Handler: SearchCategoryHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/tags/search",
					Handler: SearchTagHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/articles/images",
					Handler: UploadImageHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/admin"),
	)
}
