dev:
  Name: blog-api
  Host: 0.0.0.0
  Port: 8888

  mysql:
    host: 127.0.0.1
    port: 3306
    username: root
    password: zhangphh=520
    database_name: zhangphh_blogs
  
  redis:
    host: 127.0.0.1
    port: 6379
    password: ""
    db: 1
    pool_size: 50
    min_idle_conns: 10
    max_retries: 3